### PR TITLE
Issue 24

### PR DESCRIPTION
**Pull request by andreaturli**

### CODE REVIEW

**Comment by andreaturli** [comment]
the build fails for a different problem that we may fix later.

@aledsage can you review that?

**Comment by googlielmo** [comment]
Hi. Added one commit to fix the conversion from href to vApp id urn

**Comment by nakomis** [comment]
It looks like this re-introduces the issue in #26. I've tried merging both branches, but the error still occurs (see comments on #26)

**Comment by andreaturli** [comment]
closed in favor of #27

**Pull request closed without merging**
