### PR TITLE
fix listImages when a vAppTemplate in FAILED_CREATION

### PR DESCRIPTION
**Pull request by andreaturli**
- only considers vAppTemplate in POWERED_OFF mode

@nakomis could you please have a look?

### CODE REVIEW

**Comment by nakomis** [comment]
This looks good, but testing it will require creating a template in FAILED_CREATION state, which will effectively block the rest of the team from deploying, so I've scheduled a maintenance window

**Comment by aledsage** [comment]
@andreaturli can you take a look at the failing test - travis reports:

```
Failed tests: 
  EnvelopeTest.testUnmarshallEnvelope:43 » Unmarshal
```

@nakomis we'll leave you to test this during the customer's maintenance window.

**Comment by andreaturli** [comment]
@aledsage it should be already fixed at https://github.com/cloudsoft/jclouds-vcloud-director/commit/b7cc48fe73e085a2e599003dffb2a49fa4d61049

**Comment by andreaturli** [comment]
I'd probably need to rebase that. Let's do it so to trigger another build

**Comment by aledsage** [comment]
Merging.

**Pull request merged**
