### PR TITLE
Reduce poll intervals for tasks

### PR DESCRIPTION
**Pull request by bostko**
Related to https://github.com/cloudsoft/jclouds-vcloud-director/issues/40

### CODE REVIEW

**Comment by bostko** [comment]
I tested that and it takes no affect on behavior again two blueprints are deployed at the end.
13 blueprints were longer in progress and two succeeded.
 However I think it won't hurt if we merge it :D

**Comment by ivanayov** [comment]
LGTM

**Comment by bostko** [comment]
I will parametrize it at some point so I can try with bigger timeouts.
However I remember there was problem passing jclouds parameters from Apache Brooklyn for some clouds, hope I can handle that.

**Comment by bostko** [comment]
Already merged.

**Pull request closed without merging**
